name: Install assisted-mindfulness

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [8.2, 8.1, 8.0]
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: P${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Setup PHP 🔧
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, fileinfo, exif
          coverage: none
          tools: composer:v2

      - name: Install dependencies 🔧
        run: |
          composer require "assisted-mindfulness/naive-bayes" --no-interaction --prefer-dist
          composer remove "assisted-mindfulness/naive-bayes"
          composer require "assisted-mindfulness/browsershot" --no-interaction --prefer-dist
          composer remove "assisted-mindfulness/browsershot"
          composer require "esplora/memento" --no-interaction --prefer-dist
          composer remove "esplora/memento"
          composer require "motomedialab/laravel-vite-helper" --no-interaction --prefer-dist
          composer remove "motomedialab/laravel-vite-helper"
          composer require "assisted-mindfulness/bayesian-average" --no-interaction --prefer-dist
          composer remove "assisted-mindfulness/bayesian-average"
          composer require "esplora/next-value-predictor" --no-interaction --prefer-dist
          composer remove "esplora/next-value-predictor"
          composer require "esplora/similar" --no-interaction --prefer-dist
          composer remove "esplora/similar"
          composer require "esplora/auto-login" --no-interaction --prefer-dist
          composer remove "esplora/auto-login"
          
          
